### ISSUE TITLE
Dependency on SwiftkubeModel is too loose

### ISSUE THREAD

**Issue by allenhsu** [swiftkube/client#10]
It seems that minor versions of `SwiftkubeModel` are not backward compatible. For example `settings` has been removed from `SwiftkubeModel` `0.4.0`, however it's used in `SwiftkubeClient` `0.9.0`. So installing `SwiftkubeClient` `0.9.0` without manually pinning `SwiftkubeModel` to `0.3.x` in the main project would cause the project failing to compile.

So, I would recommend updating the dependency on `SwiftkubeModel` to `upToNextMinor` in `Package.swift`.

**Comment by iabudiab** [comment]
@allenhsu Yes, you are absolutely right. From `SwiftkubeClient 0.10.0` forward it will be the case, which will be released this week.
