### ISSUE TITLE
Support to extend with custom models 

### ISSUE THREAD

**Issue by petershaw** [swiftkube/client#13]
I need to list all resources of 

```
apiVersion: cert-manager.io/v1
kind: Certificate
```

it there is any way to implement own Models to support crds? 
The code looks very extensable at the first look. Feature-Request is to have a documentation how to implement an extension to support cruds on custom resources.

Will this be possible?

**Comment by iabudiab** [comment]
Hey there. It is currently not possible, however, CRD support is on the top of the to-do list 😉
One thing I could prioritize is support for the `unstructured` resource type as a catch-all-fallback.
I'll try to find some time over the next couple of days, maybe the weekend, to squeeze a first implementation for `unstructured` types.

Cheers

**Comment by petershaw** [comment]
Hey @iabudiab 
wonderful! And a big thanks to your work. I will spread the word!

**Comment by iabudiab** [comment]
@petershaw You should check out the new version ;)

**Comment by iabudiab** [comment]
Landed in v0.13.0
