### ISSUE TITLE
Structured Concurrency for `watch`

### ISSUE THREAD

**Issue by t089** [swiftkube/client#25]
Currently, watching a resource or list of resources runs the notification callback in a block that is executed on one of the client's event loops. When using structured concurrency, it requires to spawn new `Tasks` and call out to those from the callback, which might have weird effects on the ordering of events.

**Comment by iabudiab** [comment]
Yes 😅 this was on my Todo list and I was hoping to rollout an update before somebody runs into problems. I guess, you beat me there.

**Comment by t089** [comment]
No worries, I am well aware that this is under active development. Just to make sure it is tracked. Happy to help if I can, although my time is very limited as well unfortunately.
Are you thinking of making the watch an `AsyncStream`?

**Comment by iabudiab** [comment]
To be honest, I don't know yet. `AsyncStream` seams like the obvious choice here, but we'll see 😄
