### ISSUE TITLE
Consider adding `Equatable` to generated models

### ISSUE THREAD

**Issue by t089** [swiftkube/client#28]
Would it be a good idea to add `Equatable` to the generated models / types?

I ran into an issue where I reused `meta.v1.Condition` in one of my custom CRDs in the `status` property and wanted to compare if the status had changed. For that I had to implement the `Equatable` conformance manually.

**Comment by iabudiab** [comment]
I've already implemented this 😄. All the kubernetes resources will be Hashable.
I haven't pushed it yet, because I'm still testing and deciding if there is a better solution, than the one I made.
